language: scala
deploy:
  provider: releases
  api_key:
    secure: d2u0VHuO5wx+htuQONiWVx1c5PsNeQgDfjm9LYjQQSl2RK7gFqcVNZOX2DPHdxUD131caZWgdcfjdimoFtJLt/3XwC14/7aFfVz0kIcMP/yKFYxJNmSGc2HPx3iaIOemUKYe7DrcaMxbqa8xXEzmYC1cJC8FCFG2SrLKWHvsGPo=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-custom-orchestrators-plugin
notifications:
  hipchat:
    rooms:
      secure: R2E/KM4uh619oaqiQuOoR2dZ/jByflXhDRDozZqP+kMg0EMB1FkShfQsFR9oILNUGFStbW28XUH3JMfyuhD68ns48wyTbMy/6EJZ3rNf/F5USRzS3Jr3ZkHlHjgPCYsT752UFkRC7wsteAeElFl2tqA6Z9JASlvExgeHOf8DKWE=
